# Generated by Django 2.1.5 on 2019-02-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('balance', models.IntegerField(default=0)),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AccountTable')),
            ],
        ),
        migrations.CreateModel(
            name='CarLoanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.IntegerField(default=0)),
                ('monthly_expenditure', models.IntegerField(default=0)),
                ('total_asset', models.IntegerField(default=0)),
                ('car_price', models.IntegerField(default=0)),
                ('requested_loan_amount', models.IntegerField(default=0)),
                ('car_condition', models.CharField(max_length=20)),
                ('car_vendor', models.CharField(max_length=20)),
                ('car_brand', models.CharField(max_length=20)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_id', to='polls.AccountTable')),
                ('nominee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom_id', to='polls.AccountTable')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
