# Generated by Django 2.1.5 on 2019-02-12 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190212_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='carloandata',
            name='apply_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
